const mongoose = require('mongoose');

let orderSchema = mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true,
    },
    address:{
        firstname:{
            type:String,
            required:true,
        },
        mobile:{
            type:String,
            required:true,
        },
        pincode:{
            type:String,
            required:true,
        },
        address:{
            type:String,
            required:true,
        },
        housename:{
            type:String,
            required:true,
        },
        districtORcity:{
            type:String,
            required:true,
        },
        state:{
            type:String,
            required:true,
        },
    }, 
    orderItems:[{
        productId:{
            type: mongoose.Schema.Types.ObjectId,
            ref:'product',
            required:true,
        },
        category:{
            type:String,
        },
        productPrice:{
            type:Number,
            required:true,
        },
        offer:{
            type:Number,
            required:true,
        },
        quantity:{
            type:Number,
            required:true
        },
        orderStatus:{
            type:String,
            enum: ["ordered", "shipped", "delivered","cancelled","pending","returned"],
            required:true,
        },
        returnreason:{
            type:String,
        }
     }],
    price:{
        type:Number,
        required:true,
    },
    paymentMethod:{
        type:String,
        required:true
    },
    orderDate:{
        type:Date,
        default:Date.now,
    },
    deliveredDate:{
        type:Date,
    }
})

module.exports = mongoose.model('Order',orderSchema)
